---
- hosts: cloudify-manager
  vars:
    virtualenv_dir: /opt/rabbithole/env
    config_dir: /etc/opt/rabbithole
    config_filename: config.yml
    log_dir: /var/log/cloudify
    log_filename: rabbithole.log
    service_dir: /lib/systemd/system
    service_filename: rabbithole.service
    version: 0.3
    amqp:
      host: localhost
      port: 5672
      username: cloudify
      password: c10udify
    sql:
      host: localhost
      port: 5432
      dbname: cloudify_db
      username: cloudify
      password: cloudify
  tasks:
    - name: install virtualenv
      pip:
        name: virtualenv
        state: present
    - name: install rabbithole
      pip:
        name: rabbithole[postgresql]
        version: "{{ version }}"
        virtualenv: "{{ virtualenv_dir }}"
    - name: create configuration directory
      file:
        path: "{{ config_dir }}"
        state: directory
    - name: create configuration file
      template:
        src: "files/{{ config_filename }}.jinja2"
        dest: "{{ config_dir }}/{{ config_filename }}"
    - name: create service file
      template:
        src: "files/{{ service_filename }}.jinja2"
        dest: "{{ service_dir }}/{{ service_filename }}"
    - name: start service
      systemd:
        name: rabbithole
        state: started
        daemon-reload: yes
